server:
  port: 13000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://192.168.200.100:3306/gmall_order?useSSL=false

  profiles:
    include: sharding