server:
  port: 8000

spring:
#  zipkin:
#    sender:
#      type: web
#    base-url: http://192.168.200.100:9411/
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true
#  redis:
#    host: 192.168.200.100
#    password: Lfy123456
app:
  thread-pool:
    core: 2
    max: 4
    queue size: 2000
    keep-alive-time: 300
#暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"