server:
  port: 8000

spring:
  zipkin:
    sender:
      type: web
    base-url: http://192.168.200.100:9411/

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration